import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/header";

export const metadata: Metadata = {
  title: "Dev Bridge",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-background min-h-screen font-sans antialiased">
        <TRPCReactProvider>
          <header className="flex flex-col items-center border-b border-gray-200 p-5 shadow-sm">
            <div className="w-full max-w-7xl">
              <Header />
            </div>
          </header>

          <main className="flex flex-col items-center">
            <div className="relative z-10 mt-5 w-full max-w-6xl">
              {children}
            </div>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
